name: NixOS ISO torrent creator
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  
env:
  nixos_version: 22.05
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get NixOS info and version
        id: nixos-info
        run: |
          url=$(curl -sLI -o /dev/null -w %{url_effective} https://channels.nixos.org/nixos-$nixos_version)
          info=$(basename $url)
          echo ::set-output name=info::$info
          echo ::set-output name=latest-version::${info#nixos-}
          echo ::set-output name=current-version::$(curl -s $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases/latest | jq -r .tag_name)
          
      - name: Check if there is newer version
        run: '[ v${{ steps.nixos-info.outputs.latest-version }} != ${{ steps.nixos-info.outputs.current-version }} ]'
        
    outputs:
      info: ${{ steps.nixos-info.outputs.info }}
      latest-version: ${{ steps.nixos-info.outputs.latest-version }}
      
  torrent:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [plasma5, gnome, minimal]
        architecture: [x86_64, i686]
        exclude:
          - flavor: plasma5
            architecture: i686
          - flavor: gnome
            architecture: i686
            
    steps:
      - name: Get NixOS ISO URL and file name
        id: nixos-iso
        run: |
          echo ::set-output name=url::https://releases.nixos.org/nixos/$nixos_version/${{ needs.check.outputs.info }}/nixos-${{ matrix.flavor }}-${{ needs.check.outputs.latest-version }}-${{ matrix.architecture }}-linux.iso
          echo ::set-output name=filename::nixos-${{ matrix.flavor }}-${{ needs.check.outputs.latest-version }}-${{ matrix.architecture }}-linux.iso
          
      - name: Install torrenttools
        run: |
          sudo add-apt-repository ppa:fbdtemme/torrenttools
          sudo apt-get install torrenttools
          
      - name: Download NixOS ISO
        run: aria2c -x 16 "${{ steps.nixos-iso.outputs.url }}"
        
      - name: Create NixOS ISO torrent
        run: torrenttools create -o "${{ steps.nixos-iso.outputs.filename }}.torrent" -w "${{ steps.nixos-iso.outputs.url }}" -c "NixOS ${{ matrix.flavor }} ${{ matrix.architecture }} ${{ needs.check.outputs.latest-version }} torrent by AnimMouse" -s nixos-iso-torrents "${{ steps.nixos-iso.outputs.filename }}"
        
      - name: Upload NixOS ISO torrent
        uses: actions/upload-artifact@v3
        with:
          name: NixOS ${{ matrix.flavor }} ${{ matrix.architecture }}
          path: ${{ steps.nixos-iso.outputs.filename }}.torrent
          
  release:
    needs: [check, torrent]
    runs-on: ubuntu-latest
    steps:
      - name: Download NixOS ISO torrents
        uses: actions/download-artifact@v3
        
      - name: Release NixOS ISO torrents
        uses: softprops/action-gh-release@v1
        with:
          name: NixOS ${{ needs.check.outputs.latest-version }}
          tag_name: v${{ needs.check.outputs.latest-version }}
          body: |
            ${{ needs.check.outputs.info }}
          files: |
            NixOS plasma5 x86_64/nixos-plasma5-${{ needs.check.outputs.latest-version }}-x86_64-linux.iso.torrent
            NixOS gnome x86_64/nixos-gnome-${{ needs.check.outputs.latest-version }}-x86_64-linux.iso.torrent
            NixOS minimal x86_64/nixos-minimal-${{ needs.check.outputs.latest-version }}-x86_64-linux.iso.torrent
            NixOS minimal i686/nixos-minimal-${{ needs.check.outputs.latest-version }}-i686-linux.iso.torrent