name: NixOS others ISO torrent creator
on:
  schedule:
    - cron: '7 11 * * 0'
  workflow_dispatch:
  watch:
    types: [started]
    
env:
  nixos_version: 22.05
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get NixOS aarch64 info and version
        id: nixos-info
        run: |
          url=$(curl -sLI -o /dev/null -w %{url_effective} https://channels.nixos.org/nixos-$nixos_version-aarch64)
          info=$(basename $url)
          echo ::set-output name=info::$info
          echo ::set-output name=latest-version::${info#nixos-}
          echo ::set-output name=current-version::$(curl -s $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases | jq -r 'map(select(.prerelease)) | first | .tag_name')
          
      - name: Check if there is newer version
        run: '[ v${{ steps.nixos-info.outputs.latest-version }}-aarch64 != ${{ steps.nixos-info.outputs.current-version }} ]'
        
    outputs:
      info: ${{ steps.nixos-info.outputs.info }}
      latest-version: ${{ steps.nixos-info.outputs.latest-version }}
      
  torrent:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Get NixOS aarch64 ISO URL and file name
        id: nixos-iso
        run: |
          echo ::set-output name=url::https://releases.nixos.org/nixos/$nixos_version-aarch64/${{ needs.check.outputs.info }}/nixos-minimal-${{ needs.check.outputs.latest-version }}-aarch64-linux.iso
          echo ::set-output name=filename::nixos-minimal-${{ needs.check.outputs.latest-version }}-aarch64-linux.iso
          
      - name: Install torrenttools
        run: |
          sudo add-apt-repository -y ppa:fbdtemme/torrenttools
          sudo apt-get -qq -y install torrenttools
          
      - name: Download NixOS ISO
        run: aria2c -x 16 "${{ steps.nixos-iso.outputs.url }}"
        
      - name: Create NixOS ISO torrent
        run: torrenttools create -o "${{ steps.nixos-iso.outputs.filename }}.torrent" -w "${{ steps.nixos-iso.outputs.url }}" -c "NixOS minimal aarch64 ${{ needs.check.outputs.latest-version }} torrent by AnimMouse" -s nixos-iso-torrents "${{ steps.nixos-iso.outputs.filename }}"
        
      - name: Upload NixOS ISO torrent
        uses: actions/upload-artifact@v3
        with:
          name: NixOS minimal aarch64
          path: ${{ steps.nixos-iso.outputs.filename }}.torrent
          
  release:
    needs: [check, torrent]
    runs-on: ubuntu-latest
    steps:
      - name: Download NixOS ISO torrents
        uses: actions/download-artifact@v3
        
      - name: Release NixOS ISO torrents
        run: |
          gh release create "v${{ needs.check.outputs.latest-version }}-aarch64" \
          "NixOS minimal aarch64/nixos-minimal-${{ needs.check.outputs.latest-version }}-aarch64-linux.iso.torrent" \
          -n "${{ needs.check.outputs.info }} aarch64" -p -t "NixOS ${{ needs.check.outputs.latest-version }} aarch64"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}